<?php

echo "Generating autoload files...\n";

// Create vendor directory if it doesn't exist
if (!is_dir('vendor')) {
    mkdir('vendor', 0755, true);
}

// Create autoload directory
if (!is_dir('vendor/autoload.php')) {
    // Create a simple autoload file
    $autoloadContent = '<?php

// Simple autoloader for Laravel 10
spl_autoload_register(function ($class) {
    // Convert namespace to file path
    $file = __DIR__ . "/../" . str_replace("\\", "/", $class) . ".php";
    
    if (file_exists($file)) {
        require_once $file;
    }
});

// Load Composer autoloader if it exists
if (file_exists(__DIR__ . "/composer/autoload_real.php")) {
    require_once __DIR__ . "/composer/autoload_real.php";
}
';
    
    file_put_contents('vendor/autoload.php', $autoloadContent);
}

// Create composer directory
if (!is_dir('vendor/composer')) {
    mkdir('vendor/composer', 0755, true);
}

// Create a basic autoload_psr4.php
$psr4Content = '<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    "App\\\\" => array($baseDir . "/app"),
    "Illuminate\\\\" => array($baseDir . "/vendor/laravel/framework/src"),
);
';

file_put_contents('vendor/composer/autoload_psr4.php', $psr4Content);

// Create a basic autoload_classmap.php
$classmapContent = '<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
);
';

file_put_contents('vendor/composer/autoload_classmap.php', $classmapContent);

// Create a basic autoload_files.php
$filesContent = '<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
);
';

file_put_contents('vendor/composer/autoload_files.php', $filesContent);

echo "Autoload files generated successfully!\n";
echo "Note: This is a basic autoloader. For full functionality, you should run composer install on the server.\n";
